"""Course data service.

Loads the checked-in course model ``data/legs_2026.json`` (generated by
``scripts/export_course.py`` from the relay-scheduler repo) and exposes
station-name -> exchange-id resolution.

The course JSON is a build artifact (see docs/plans/leg-assignments.md, WP1):
pantograph never computes distances or elevations itself. Units are documented
in the file's ``units`` object; in short, distances (leg and commute) are
integer hundredths of a mile and ascent/descent are integer feet.

``preferred_station`` values in the database are station *names* from
``load_station_names()`` (app/utils.py, data/lrr_1_line.geojson); solver facts
and the course model use integer exchange ids. :func:`resolve_station_name`
maps between the two, covering exact exchange names, spelling variants
(``station_aliases``), and stations that are on the line but not part of this
course (``non_course_stations``, e.g. unopened infill stations) so that any
storable preference resolves to an id.
"""

import json
from functools import lru_cache

COURSE_DATA_PATH = 'data/legs_2026.json'


@lru_cache(maxsize=1)
def load_course():
    """Return the parsed course model (dict per the WP1 schema).

    Raises RuntimeError if the checked-in artifact is missing or invalid --
    this is a deployment error, not a user-recoverable condition.
    """
    try:
        with open(COURSE_DATA_PATH, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        raise RuntimeError(
            f"Course data {COURSE_DATA_PATH} is missing or invalid; "
            f"regenerate it with scripts/export_course.py ({e})"
        ) from e


@lru_cache(maxsize=1)
def station_name_to_exchange_id():
    """Mapping of every known station name/alias to its integer exchange id."""
    course = load_course()
    mapping = {exchange['name']: exchange['id'] for exchange in course['exchanges']}
    mapping.update(course.get('station_aliases', {}))
    mapping.update(course.get('non_course_stations', {}))
    return mapping


def resolve_station_name(name):
    """Resolve a station name (as stored in ``preferred_station``) to an
    exchange id, or None if the name is unknown."""
    if not name:
        return None
    return station_name_to_exchange_id().get(name.strip())


def is_course_exchange(exchange_id):
    """True if the id is an exchange of this course (has legs/commute data)."""
    return any(exchange['id'] == exchange_id for exchange in load_course()['exchanges'])


@lru_cache(maxsize=1)
def exchanges_by_id():
    """Mapping of exchange id -> exchange dict (id, name, coordinates)."""
    return {exchange['id']: exchange for exchange in load_course()['exchanges']}


@lru_cache(maxsize=1)
def commute_distances():
    """Symmetric {(id_a, id_b): distance} lookup in hundredths of a mile,
    including zero self-distances."""
    course = load_course()
    table = {}
    for a, b, dist in course['commute']:
        table[(a, b)] = dist
        table[(b, a)] = dist
    for exchange in course['exchanges']:
        table[(exchange['id'], exchange['id'])] = 0
    return table
