services:
  pantograph:
    image: pantograph:latest
    env_file:
      - .env
    build: .
    volumes:
      - "./uploads:/app/uploads"
      - "./data:/app/data"
    expose:
      - "5001"
    networks:
      - web_network

  pantograph-cron:
    image: pantograph:latest
    env_file:
      - .env
    build: .
    volumes:
      - "./uploads:/app/uploads"
      - "./data:/app/data"
    user: root # Cron won't inherit env vars from docker-compose, so we write them to a file and source that file in the cron job
    command: ["sh", "-c", "printenv | grep -v '^_' | sed 's/^/export /' > /tmp/env && echo '0 7 * * * . /tmp/env && cd /app && uv run python cron_digest.py' | crontab - && cron -f"]
    networks:
      - web_network
networks:
  web_network:
    external: true